### PR TITLE
[FIX] Bakers Dozen achievement (#3473)

### LINKED ISSUE #3473: [BUG] Baking honey cake does not increase cake counter of Bakers Dozen achievement
## Summary of Bug

Baking `Honey Cake`  does not increase the counter of `Bakers Dozen` achievement.

## Steps to Reproduce

Bake a `Honey Cake` in a `Bakery`, then recover it at the end of cooldown.

You should see that the counter of baked cakes of `Bakers Dozen` achievement has not increased.

## Expected Behavior

- Cook a `Honey Cake` in `Bakery`.
- Recover the `Honey Cake` from Bakery`.

We should have the counter of `Bakers` Dozen Achivement increased by one.

## Actual Behavior

The counter of `Bakers Dozen` achievement has not been increased.

not-counted-honey-cake

## Screenshots

**Device Information (please complete the following information):**

- Device: PC
- OS: Windows 11
- Browser/App: chrome + metamask app
- Version:  122.0.6261.95

### PR DESCRIPTION
**Pull request by sbeugnon**
# Description

When counting the number of baked cakes, the `Bakers Dozen` achievement does not count the following cakes: `Eggplant Cake`, `Orange Cake` and `Honey Cake`.
Fixes #3473 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/features/game/types/achievements.ts [hunk 1]
```diff
@@ -254,7 +254,7 @@ export const ACHIEVEMENTS: () => Record<AchievementName, Achievement> = () => ({
   "Bakers Dozen": {
     description: translate("bakersDozen.description"),
     progress: (gameState: GameState) => {
-      const cakeEvents = getKeys(CAKES()).map(
+      const cakeEvents = getKeys(COOKABLE_CAKES).map(
```
Comment (eliasSFL) [inline src/features/game/types/achievements.ts:257]:
```suggestion
      const cakeEvents = getKeys(COOKABLE_CAKES()).map(
```
You may need to add Bracket parentheses to this variable

Comment (sbeugnon) [reply src/features/game/types/achievements.ts:257]: > You may need to add Bracket parentheses to this variable

Thanks you @eliasSFL for your answer.

This is precisely one of the differences with the previous value `CAKES`, which was a function. Here, `COOKABLE_CAKES` is a `Record<CookableName, Cookable>`. As a result, the () operator is not defined.

So I took inspiration from the solution used for the `Kiss the Cook` achievement, which uses the COOKABLES variable (which is also a `Record<CookableName,Cookable>`).

Comment (eliasSFL) [reply src/features/game/types/achievements.ts:257]: Oh I see. Thanks for letting me know, I'm still learning as I go even though I've been contributing code for a while now.

**Review by spencerdezartsmith — APPROVED** [review]
LGTM
