### PR TITLE
[FIX] Seed stock wrapping onto next line

### LINKED ISSUE #335: [BUG] Seed Stock Mobile issue
On mobile, the seed stock is wrapping onto the line of text (see attached).

**Expected Behaviour**

A user should be able to see the seeds in stock, and all of the image/text below when on mobile or desktop

IMG_4529

### PR DESCRIPTION
**Pull request by jcads**
# Description

- Created a reusable component for Stocks
- Fixed wrapping on mobile

Fixes #335 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

manually
image

# Checklist:

- [x] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]
- [x] Screenshot if it includes any UI changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/components/ui/Stock.tsx [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+interface Props {
+    item: Craftable
+}
+
+export const Stock: React.FC<Props> = ({ item }) => {
+  const { gameService } = useContext(Context);
+  const [{ context: { state }}] = useActor(gameService);
+  const stock = state.stock[item.name] || new Decimal(0);
+  const isLimitedItem = item.name in Object.keys(LimitedItems);
```
Comment (j923sneaks) [inline src/components/ui/Stock.tsx:17]: Suggestion to use `hasOwnProperty()` to avoid creating keys array. Might need to typecast `LimitedItems` as `Object`

```
const isLimited = LimitedItems.hasOwnProperty(item.name);
```

Comment (jcads) [reply src/components/ui/Stock.tsx:17]: Yeah I think I missed this. Thanks

**Review by adamhannigan — APPROVED** [review]
LGTM, nice work 👏
